// Fallback demo parcels matching the five markets from the mockup.
// Used when live ArcGIS endpoints are unavailable.

export const MOCK_MARKETS = {
  Tippecanoe: [
    { id: 'mock-1', lat: 40.4198, lng: -86.91, address: '2450 Sagamore Pkwy S', city: 'Lafayette, IN 47905', type: 'Retail / Strip Commercial', zoning: 'C2', county: 'Tippecanoe', acres: 1.8, sqft: 12400, assessed: 1850000, lastSale: 2400000, lastSaleYear: 2021, capRate: 6.4, tag: '0.4 mi from Purdue main gate', highlight: 'High foot traffic corridor serving student and faculty population. C2 zoning permits restaurant, retail, and service uses by right.', badge: 'Purdue Corridor', owner: { entity: 'West Lafayette Retail Partners LLC', type: 'Indiana LLC', principal: 'David R. Harrington', role: 'Managing Member', address: '4820 W 96th St, Indianapolis, IN 46268', holdingYears: 10, sosUrl: 'https://bsd.sos.in.gov/' }, geometry: null, _mock: true },
    { id: 'mock-2', lat: 40.428, lng: -86.905, address: '3810 State Road 26 E', city: 'Lafayette, IN 47905', type: 'General Commercial', zoning: 'C2', county: 'Tippecanoe', acres: 2.3, sqft: 9800, assessed: 1240000, lastSale: 1650000, lastSaleYear: 2019, capRate: 5.9, tag: '1.1 mi from campus', highlight: 'Larger lot with older improvements — potential value-add play. Zoning supports redevelopment.', badge: null, owner: { entity: 'Tippecanoe Commercial Holdings', type: 'Indiana LLC', principal: 'Susan M. Kowalski', role: 'Managing Member', address: 'PO Box 4412, Lafayette, IN 47902', holdingYears: 16, sosUrl: 'https://bsd.sos.in.gov/' }, geometry: null, _mock: true },
    { id: 'mock-3', lat: 40.426, lng: -86.919, address: '521 Chauncey Ave', city: 'West Lafayette, IN 47906', type: 'Mixed-Use', zoning: 'MU', county: 'Tippecanoe', acres: 0.6, sqft: 5200, assessed: 980000, lastSale: 1300000, lastSaleYear: 2022, capRate: 7.1, tag: 'Steps from campus', highlight: 'Chauncey Hill corridor — highest-demand retail and dining strip in the market. MU zoning allows ground-floor commercial with residential above.', badge: 'Purdue Corridor', owner: { entity: 'Chauncey Development Group LLC', type: 'Indiana LLC', principal: 'Thomas P. Nguyen', role: 'Managing Member', address: '622 Brown St, West Lafayette, IN 47906', holdingYears: 5, sosUrl: 'https://bsd.sos.in.gov/' }, geometry: null, _mock: true },
  ],
  Boone: [
    { id: 'mock-4', lat: 40.052, lng: -86.465, address: '1204 W State Road 32', city: 'Lebanon, IN 46052', type: 'Industrial / Light Mfg', zoning: 'I1', county: 'Boone', acres: 12.4, sqft: 0, assessed: 2100000, lastSale: 1800000, lastSaleYear: 2020, capRate: null, tag: '1.2 mi from Lilly LEAP site', highlight: 'Undeveloped industrial parcel adjacent to the Lilly LEAP manufacturing corridor. Assessed value likely to rise significantly as megasite infrastructure comes online.', badge: 'Near Lilly LEAP', owner: { entity: 'Boone County Land Trust LLC', type: 'Indiana LLC', principal: 'Robert J. Stanton', role: 'Managing Member', address: '112 W Washington St, Lebanon, IN 46052', holdingYears: 21, sosUrl: 'https://bsd.sos.in.gov/' }, geometry: null, _mock: true },
    { id: 'mock-5', lat: 40.044, lng: -86.469, address: '890 N Lebanon St', city: 'Lebanon, IN 46052', type: 'General Commercial', zoning: 'C2', county: 'Boone', acres: 3.1, sqft: 8200, assessed: 890000, lastSale: 1100000, lastSaleYear: 2018, capRate: 5.8, tag: '2.0 mi from Lilly LEAP site', highlight: 'Commercial parcel on Lebanon\'s main corridor. Workforce demand will increase materially as Lilly\'s site reaches full employment.', badge: 'Near Lilly LEAP', owner: { entity: 'Lebanon Commercial Properties LLC', type: 'Indiana LLC', principal: 'Patricia L. Hendricks', role: 'Managing Member', address: '55 E Washington St Ste 200, Lebanon, IN 46052', holdingYears: 13, sosUrl: 'https://bsd.sos.in.gov/' }, geometry: null, _mock: true },
    { id: 'mock-6', lat: 40.058, lng: -86.474, address: '3300 N Lebanon Corporate Dr', city: 'Lebanon, IN 46052', type: 'Flex / Office-Warehouse', zoning: 'I2', county: 'Boone', acres: 6.8, sqft: 24000, assessed: 3200000, lastSale: 4100000, lastSaleYear: 2023, capRate: 6.9, tag: '0.6 mi from Lilly LEAP site', highlight: 'Closest available commercial parcel to the Lilly megasite boundary. Flex industrial layout suits supplier or logistics tenants.', badge: 'Near Lilly LEAP', owner: { entity: 'Meridian Industrial Partners LLC', type: 'Indiana LLC', principal: 'James A. Whitfield', role: 'Managing Member', address: '8888 Keystone Crossing Ste 1300, Indianapolis, IN 46240', holdingYears: 4, sosUrl: 'https://bsd.sos.in.gov/' }, geometry: null, _mock: true },
  ],
  Hamilton: [
    { id: 'mock-7', lat: 39.972, lng: -86.1195, address: '731 S Rangeline Rd', city: 'Carmel, IN 46032', type: 'General Commercial', zoning: 'C2', county: 'Hamilton', acres: 1.24, sqft: 8400, assessed: 1420000, lastSale: 2100000, lastSaleYear: 2019, capRate: 6.1, tag: 'Near Arts & Design District', highlight: 'High-traffic Rangeline Road segment near the CRC redevelopment boundary. C2 zoning, older improvements — potential value-add angle.', badge: 'CRC Adjacent', owner: { entity: 'Carmel Retail Holdings LLC', type: 'Indiana LLC', principal: 'Michael T. Brennan', role: 'Managing Member', address: '12800 N Meridian St Ste 400, Carmel, IN 46032', holdingYears: 14, sosUrl: 'https://bsd.sos.in.gov/' }, geometry: null, _mock: true },
    { id: 'mock-8', lat: 39.98, lng: -86.117, address: '1140 N Rangeline Rd', city: 'Carmel, IN 46032', type: 'Retail / Restaurant', zoning: 'C1', county: 'Hamilton', acres: 0.8, sqft: 4200, assessed: 920000, lastSale: 1350000, lastSaleYear: 2021, capRate: 5.5, tag: 'Midtown Carmel corridor', highlight: 'Smaller format parcel in Midtown Carmel. C1 zoning suits neighborhood-serving retail. High Rangeline visibility.', badge: null, owner: { entity: 'Rangeline Partners LLC', type: 'Indiana LLC', principal: 'Karen S. Volpe', role: 'Managing Member', address: 'PO Box 2201, Carmel, IN 46082', holdingYears: 8, sosUrl: 'https://bsd.sos.in.gov/' }, geometry: null, _mock: true },
    { id: 'mock-9', lat: 39.9755, lng: -86.121, address: '520 S Rangeline Rd', city: 'Carmel, IN 46032', type: 'Mixed-Use', zoning: 'MU', county: 'Hamilton', acres: 1.05, sqft: 11200, assessed: 2650000, lastSale: 3800000, lastSaleYear: 2022, capRate: 7.3, tag: 'Arts & Design District', highlight: 'Prime mixed-use parcel inside the Arts & Design District. Among the highest-demand locations in the Carmel submarket.', badge: 'CRC Adjacent', owner: { entity: 'Carmel Arts District Holdings LLC', type: 'Indiana LLC', principal: 'William R. Eckert', role: 'Managing Member', address: 'One Indiana Square Ste 2800, Indianapolis, IN 46204', holdingYears: 7, sosUrl: 'https://bsd.sos.in.gov/' }, geometry: null, _mock: true },
  ],
  Monroe: [
    { id: 'mock-11', lat: 39.168, lng: -86.521, address: '401 E Kirkwood Ave', city: 'Bloomington, IN 47408', type: 'Mixed-Use / Retail', zoning: 'MU', county: 'Monroe', acres: 0.5, sqft: 7200, assessed: 1450000, lastSale: 2200000, lastSaleYear: 2021, capRate: 7.4, tag: 'Kirkwood Ave entertainment corridor', highlight: 'Kirkwood Avenue is Bloomington\'s primary entertainment and dining corridor. Extremely high foot traffic year-round, with strong student, faculty, and visitor demand.', badge: 'IU Corridor', owner: { entity: 'Kirkwood Avenue Properties LLC', type: 'Indiana LLC', principal: 'Gregory S. Palmer', role: 'Managing Member', address: '116 W 6th St Ste 300, Bloomington, IN 47404', holdingYears: 12, sosUrl: 'https://bsd.sos.in.gov/' }, geometry: null, _mock: true },
    { id: 'mock-12', lat: 39.172, lng: -86.519, address: '2815 E 10th St', city: 'Bloomington, IN 47408', type: 'General Commercial', zoning: 'C2', county: 'Monroe', acres: 1.9, sqft: 10400, assessed: 980000, lastSale: 1450000, lastSaleYear: 2018, capRate: 6.2, tag: 'East side commercial corridor', highlight: 'Active commercial corridor serving east Bloomington and the student residential district. Older improvements present a value-add opportunity.', badge: null, owner: { entity: 'East Bloomington Commercial LLC', type: 'Indiana LLC', principal: 'Linda M. Forsythe', role: 'Managing Member', address: 'PO Box 7741, Bloomington, IN 47407', holdingYears: 15, sosUrl: 'https://bsd.sos.in.gov/' }, geometry: null, _mock: true },
    { id: 'mock-13', lat: 39.159, lng: -86.531, address: '1320 W 7th St', city: 'Bloomington, IN 47404', type: 'Flex / Research', zoning: 'I1', county: 'Monroe', acres: 3.4, sqft: 18000, assessed: 2100000, lastSale: 2900000, lastSaleYear: 2022, capRate: 6.7, tag: 'Near IU Research & Technology Park', highlight: 'Flex industrial parcel adjacent to the IU Research and Technology Park corridor. Growing biotech and life sciences presence in this submarket.', badge: 'IU Tech Park', owner: { entity: 'Monroe Research Properties LLC', type: 'Indiana LLC', principal: 'Raymond T. Choi', role: 'Managing Member', address: '200 S Woodlawn Ave Ste 100, Bloomington, IN 47401', holdingYears: 7, sosUrl: 'https://bsd.sos.in.gov/' }, geometry: null, _mock: true },
  ],
}

export function getMockParcels(county) {
  return MOCK_MARKETS[county] || MOCK_MARKETS.Hamilton
}
